name: mental_health_app
description: A Flutter mental health chat app with AI assistant.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  auth0_flutter: ^1.6.0
  http: ^1.2.2
  lottie: ^3.1.3
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  go_router: ^14.3.0
  equatable: ^2.0.7
  flutter_client_sse: ^2.0.0    # ✅ replacement for eventsource
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/loading.json
    - assets/animations/success.json
    - assets/animations/landing.json