name: MitraSetu
description: A Flutter mental health chat app with AI assistant.

publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # auth0_flutter: ^1.5.0   # latest
  http: ^1.1.0
  lottie: ^2.7.0
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.6
  go_router: ^14.2.0
  equatable: ^2.0.5
  # Use one of the following for SSE:
  flutter_client_sse: ^2.0.3
  # flutter_http_sse: ^1.0.4
  shared_preferences: ^2.2.3
  auth0_flutter: ^1.3.0 # Latest version
  js: ^0.6.4 # For JavaScript interop on web

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/loading.json
    - assets/animations/success.json
    - assets/animations/landing.json
