name: mitrasetu
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scikit-learn
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8  # GPU support (NVIDIA CUDA 11.8)
  - tensorflow
  - jupyterlab          # optional, for running notebooks
  - pip:
      - datasets
      - transformers
      - evaluate
      - -e .
      - wandb
      - matplotlib